- name: "Install 'xdg-user-dirs' package"
  ansible.builtin.package:
    name: 'xdg-user-dirs'
    state: present
  become: true
  become_user: root

- name: "Configure xdg-user-dirs for user '{{ user_name }}'"
  ansible.builtin.command: xdg-user-dirs-update
  become: true
  become_user: "{{ user_name }}"
  changed_when: false

